# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # npm dependencies
  - package-ecosystem: "npm"  # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps): :pushpin:"
    labels:
      - "dependencies"
      - "automated"
    groups:
      non-breaking-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      nextjs-ecosystem:
        patterns:
          - "next*"
          - "react*"
          - "@next/*"
        update-types:
          - "major"
      mdx-ecosystem:
        patterns:
          - "*mdx*"
          - "remark-*"
          - "rehype-*"
        update-types:
          - "major"
      styling-packages:
        patterns:
          - "tailwindcss*"
          - "@tailwindcss/*"
          - "tw-*"
        update-types:
          - "major"
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "@types/*"
        update-types:
          - "major"
      dev-tooling:
        patterns:
          - "@biomejs/*"
          - "babel-*"
        update-types:
          - "major"
